%YAML 1.1
---
version: '>=0.0.0 || @head'
export: |
    project "NanoRange"
        kind "StaticLib"
        zpm.export [[
            includedirs "include"
            cppdialect "C++17"
        ]]
...